[wip] Move activation of dispatchers into event loop thread
confluentinc/confluent-kafka-javascript pull request #190
Opened 2024-11-27 09:40 UTC by milindl

(PR still in progress).

1. Reduce test flakiness by adding some time for metadata to propagate, adding some 'sleep's, and disabling two tests which are flaky for librdkafka-reasons.
2. Move the event-loop-thread specific stuff onto that thread.
3. See if this makes tests run on semaphore consistently.

2024-12-11 15:37 UTC, emasab requested changes
Thanks for the fix Milind and thanks @trevorr for finding it!
I request just a few changes to solve the flakiness in a different way.

2024-12-11 15:37 UTC, emasab commented on test/promisified/admin/describe_groups.spec.js
> +        expect(describeGroupsResult.groups[0].state === ConsumerGroupStates.EMPTY || describeGroupsResult.groups[0].state === ConsumerGroupStates.DEAD).toBeTruthy();
I think this won't be needed if some offsets are consumed and committed by the consumer. In that case even if there's a coordinator change, the group would be loaded and be EMPTY instead of DEAD.

2024-12-11 15:37 UTC, emasab commented on test/promisified/consumer/consumeMessages.spec.js
> +            'linger.ms': 1,
It's ensured better  with:
```suggestion
           'batch.num.messages': 1,
```

2024-12-11 15:37 UTC, emasab commented on test/promisified/consumer/consumeMessages.spec.js
> +            'message.max.bytes': 1000,
We  can leave only this one to get a single batch
```suggestion
            'fetch.message.max.bytes': 1,
```

2024-12-11 15:37 UTC, emasab commented on test/promisified/consumer/consumeMessages.spec.js
> +        }
We can verify it with `partitionsConsumedConcurrently >= 2`
If you set
```c
        const messagesConsumed = [];
        const expectedMaxConcurrentWorkers = Math.min(partitionsConsumedConcurrentlyDiff, partitions);
        const maxConcurrentWorkersReached = new DeferredPromise();
``` 
and then
```c
            eachMessage: async event => {
                inProgress++;
                messagesConsumed.push(event);
                inProgressMaxValue = Math.max(inProgress, inProgressMaxValue);
                if (inProgressMaxValue >= expectedMaxConcurrentWorkers) {
                    maxConcurrentWorkersReached.resolve();
                } else if (messagesConsumed.length > 30) {
                    await sleep(1000);
                }
                inProgress--;
            },
``` 
and finally
```c
       await maxConcurrentWorkersReached;
       expect(inProgressMaxValue).toBe(expectedMaxConcurrentWorkers);
``` 
the sleep inside the invocation makes sure that worker invocations can overlap and reach that value. First messages are skipped as there's the exponential cache growth.

2024-12-11 15:37 UTC, emasab commented on test/promisified/testhelpers.js
`DeferredPromise` can be imported and exported from here for usage from rest of the tests.

2024-12-11 15:37 UTC, emasab commented on test/promisified/testhelpers.js
> +        common['log_level'] = 1;
Let's keep the logs with level <= 5 (NOTICE) . Otherwise we could not see some error or warning. If there are expected errors in the tests a custom logger could be added later to assert their message and avoid logging it.

2024-12-11 15:37 UTC, emasab commented on test/promisified/admin/describe_groups.spec.js
> +                isSimpleConsumerGroup: expect.any(Boolean),
In case it works, this change could be reverted

2024-12-12 06:23 UTC, milindl commented on test/promisified/consumer/consumeMessages.spec.js
> +        }
I got good results on making this change but I changed `messagesConsumed.length > 30` to `messagesConsumed.length > 2048`. As it will make sure we've completely maxed out the cache capacity by this time.

2024-12-12 13:51 UTC, emasab approved these changes
LGTM!

2024-12-12 13:52 UTC, merged