Update INTRODUCTION.md with promisified API
confluentinc/confluent-kafka-javascript pull request #211
Opened 2024-12-13 12:13 UTC by milindl

1. What the title says.
2. Also update MIGRATION with the particular version of node-rdkafka migration we support.
3. I think it's _mostly_ complete. I will link to the API docs whenever I've mentioned them once they are online. This can be in a follow up PR.

2024-12-13 15:15 UTC, nhaq-confluent approved these changes

2024-12-14 14:18 UTC, emasab requested changes

2024-12-14 14:18 UTC, emasab commented on MIGRATION.md
> +For later releases, the node-rdkafka API diverges from this library. If you encounter any issues migrating, refer to the [INTRODUCTION.md](./INTRODUCTION.md) for a guide to using this library.
```suggestion
For releases > v2.17.0, the node-rdkafka API diverges from this library. If you encounter any issues migrating, refer to the [INTRODUCTION.md](./INTRODUCTION.md) for a guide to using this library.
```

2024-12-16 06:02 UTC, milindl commented on MIGRATION.md
> +For later releases, the node-rdkafka API diverges from this library. If you encounter any issues migrating, refer to the [INTRODUCTION.md](./INTRODUCTION.md) for a guide to using this library.
Did but with ` > v2.18.0`

2024-12-16 11:14 UTC, emasab commented on MIGRATION.md
> +For later releases, the node-rdkafka API diverges from this library. If you encounter any issues migrating, refer to the [INTRODUCTION.md](./INTRODUCTION.md) for a guide to using this library.
Right, because we did this [merge](https://github.com/confluentinc/confluent-kafka-javascript/commit/7f2718abf28daee03419fb309b61c94599f0b548)

2024-12-16 11:16 UTC, emasab approved these changes

2024-12-16 12:22 UTC, merged