List consumer group offsets
confluentinc/confluent-kafka-javascript pull request #49
Opened 2024-05-21 10:01 UTC by PratRanj07

Created ListConsumerGroupOffsets API with the name of fetchOffsets and wrote examples and test cases for it.

2024-05-29 08:22 UTC, milindl requested changes
Good work @PratRanj07  to implement this. 

I have done a first round of review.
Things still pending to be reviewed by me:
1. example added
2. run leak checks with valgrind 

and of course any changes you make due to the comments.

2024-05-29 08:22 UTC, milindl commented on test/promisified/admin/list_consumer_group_offsets.spec.js
> +  test("should return correct offset after consuming messages", async () => {
- add a test with `topics` unset or null too
- add a test with multiple topics each with more than 1 partition so the result format can be verified

2024-05-29 08:22 UTC, milindl commented on test/promisified/admin/list_consumer_group_offsets.spec.js
> +jest.setTimeout(30000);
rename this file to be same as the function name. Let's call it 'list consumer groups' only when we actually need to call into librdkafka. Otherwise it gets confusing to mix the names.

2024-05-29 08:22 UTC, milindl commented on types/kafkajs.d.ts
> +export type TopicInput = string | { topic: string; partitions: number[] }
To be consistent with how we have done things before, define these types in rdkafka.d.ts, and import them here. Re-export from this file. (See the top of this file for examples, one such type is `GroupOverview`)

2024-05-29 08:22 UTC, milindl commented on types/rdkafka.d.ts
> +import { FetchOffsetsPartition, Kafka, TopicInput } from './kafkajs';
Remove this line entirely after following the comment from kafkajs.d.ts (`Kafka` was unused anyway)

2024-10-18 17:58 UTC, EricMCornelius commented
Any ETA on this?  You guys are promoting this client as a KafkaJS replacement while lacking some pretty basic functionality on the admin side here...

2024-10-18 18:00 UTC, EricMCornelius commented
https://github.com/confluentinc/confluent-kafka-javascript/blob/master/MIGRATION.md#admin-client

At the very least, maybe keep major omissions up to date in any migration guides?

2024-10-21 12:03 UTC, emasab commented on types/rdkafka.d.ts
> +    fetchOffsets(options: { groupId: string,
for the `node-rdkafka` API, it's a new method, so we should have the same signature and name as `listConsumerGroupOffsets`, allowing multiple groups. In future, we'll deprecate `fetchOffsets` and have a new method named `listConsumerGroupOffsets` in KafkaJS API too.

2024-10-22 07:43 UTC, milindl requested changes
Thanks for the changes! 

Please also add a CHANGELOG.md entry, and merge the master branch to it. Once you do that we will change the base branch of this PR to master.

2024-10-22 07:43 UTC, milindl commented on src/admin.cc
> +    // Change the type of the 'error' pointer to 'const rd_kafka_error_t *'
Let's move this processing outside this function and let the caller process this. This sort of works for now, but when/if we add the capacity for multiple groups, it won't.

Let's handle only top level errors here, and move this group-specific errors out.

2024-10-22 07:43 UTC, milindl commented on src/admin.cc
> +    // Change the type of the 'error' pointer to 'const rd_kafka_error_t *'
So with the change that Emanuele suggested, you will need to change the FromFetchOffsetsResult function as well, since the return type signature will be different for listConsumerGroupOffsets.

However, the kafkajs-compatible signature remains the same, so you'll need to convert it in `fetchOffsets` in _admin.js

2024-10-22 07:43 UTC, milindl commented on test/promisified/admin/fetch_offsets.spec.js
> +            await consumer.stop();
Remove as this has no effect, here and elsewhere

2024-10-22 07:43 UTC, milindl commented on test/promisified/admin/fetch_offsets.spec.js
> +          if (error.message.includes("Offset out of range")) {
I'm not sure when you'll get this error, because it's handled automatically. Maybe remove the try-catch block entirely?

Here, and elsewhere.

2024-10-22 07:43 UTC, milindl commented on test/promisified/admin/fetch_offsets.spec.js
> +    await createTopic({ topic: topicName, partitions: 1 });
Make it similar to the other tests. Consumer, producer can also be initialized in beforeEach unless you have to pass them some special parameters. This will make the tests a lot shorter.

2024-10-22 07:43 UTC, milindl commented on test/promisified/admin/fetch_offsets.spec.js
> +        partitions: [{ partition: 0, offset: 5 }],
Wouldn't this be 5+10 instead for this case? or perhaps I've missed something in the test

2024-10-22 07:43 UTC, milindl commented on src/common.h
> +}// namespace Admin
nit
```suggestion
} // namespace Admin
```

2024-10-22 07:43 UTC, milindl commented on src/workers.cc
> + * topic offsets.
```suggestion
 * groups' topic partitions.
```

2024-10-25 10:36 UTC, PratRanj07 commented on test/promisified/admin/fetch_offsets.spec.js
> +    await createTopic({ topic: topicName, partitions: 1 });
Moved all others except createTopic as we will be creating topics with customised number of partitions for the test

2024-10-30 12:41 UTC, milindl requested changes
Pretty good work to address the review comments. I added a final set of comments, please take a look

2024-10-30 12:41 UTC, milindl commented on examples/kafkajs/fetchOffsets.js
> +// require('kafkajs') is replaced with require('@confluentinc/kafka-javascript').KafkaJS.
Use arguments for bootstrap server, requireStableOffsets and timeout. Use positionals for the group name and the topic/partitions as you are currently doing, it will be something like

```
  const args = parseArgs({
    allowPositionals: true,
    options: {
      'bootstrap-servers': {
        type: 'string',
        short: 'b',
        default: 'localhost:9092',
      },
      'timeout': {
        type: 'string',
        short: 'm',
        default: 5000,
      },
...
    },
  });

and then args.values will contain option values, and args.positionals will contain the rest of the arguments which you can parse with your function that you've already written.

2024-10-30 12:41 UTC, milindl commented on src/admin.cc
> +        listGroupOffsets->Get(context, i).ToLocalChecked().As<v8::Object>();
Here and at other places, use Nan::Get instead. You don't need to make the context either. Handle the error case properly too, in case the user has not provided a proper object.
```js
    v8::Local<v8::Value> listGroupOffsetValue = Nan::Get(listGroupOffsets, i).ToLocalChecked();
    if (!listGroupOffsetValue->IsObject()) {
      return Nan::ThrowError("Each entry must be an object");
    }
    v8::Local<v8::Object> listGroupOffsetObj = listGroupOffsetValue.As<v8::Object>();
```

2024-10-30 12:41 UTC, milindl commented on src/common.cc
> +    v8::Local<v8::Value> topicVal =
Just use `GetParameter<std::string>` to get the string of the topic name directly, no need for isolate/context. The "item" is an object and thus can be used with `GetParameter<std::string>`. 

Same goes for partitionVal and offset also.

2024-10-30 12:41 UTC, milindl commented on src/admin.cc
> +  rd_kafka_ListConsumerGroupOffsets_t **requests =
Add a comment above this telling the reader that the ownership for this is taken by Workers::AdminClientListConsumerGroupOffsets and freeing it is also handled by that class.

2024-10-30 12:41 UTC, milindl commented on src/common.cc
> +        RdKafka::ErrorCode code = static_cast<RdKafka::ErrorCode>(partition->err);
Add // NOLINT or split into two lines.

2024-11-04 06:17 UTC, milindl approved these changes
Great work. I'm approving the PR. There are some minor changes suggested. You can make them and merge this in.

2024-11-04 06:17 UTC, milindl commented on CHANGELOG.md
>  # confluent-kafka-javascript v0.3.1
0.3.1 isn't released yet so remove this section and add "1. Fixes an issue where headers were not passed correctly to the `eachBatch` callback (#130)." within this list only. Call it "Enhancements" instead of features.

2024-11-04 06:17 UTC, milindl commented on types/kafkajs.d.ts
> +    resolveOffsets?: boolean,
Sorry I missed this earlier, remove `resolveOffsets` from the types. For users of typescript this makes their life better as they get a compile-time error instead of a run time error.

2024-11-04 06:17 UTC, milindl commented on examples/kafkajs/admin/fetchOffsets.js
nit:
rename this file to fetch-offsets.js

2024-11-04 06:44 UTC, milindl approved these changes

2024-11-04 06:52 UTC, merged